### ISSUE TITLE
플러그인 추가가 안되는데 어떻게 하나요?

### ISSUE THREAD

**Issue by ghost** [monun/series-survival#2]
```
        [12:30:32 ERROR]: Could not load 'plugins\Survival.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Kotlin. Please download and install Kotlin to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.5.jar:git-Paper-602]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-602]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[12:30:32 INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b499
[12:30:33 INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:30:33 INFO]: [ProtocolLib] Enabling ProtocolLib v4.6.1-SNAPSHOT-b499
[12:30:33 INFO]: [ProtocolLib] Started structure compiler thread.
[12:30:33 INFO]: Preparing level "world"
[12:30:33 INFO]: Preparing start region for dimension minecraft:overworld
[12:30:34 INFO]: Loaded 0 spawn chunks for world world
[12:30:34 INFO]: Preparing spawn area: 0%
[12:30:34 INFO]: Time elapsed: 337 ms
[12:30:34 INFO]: Preparing start region for dimension minecraft:the_nether
[12:30:34 INFO]: Loaded 0 spawn chunks for world world_nether
[12:30:34 INFO]: Time elapsed: 210 ms
[12:30:34 INFO]: Preparing start region for dimension minecraft:the_end
[12:30:34 INFO]: Loaded 0 spawn chunks for world world_the_end
[12:30:34 INFO]: Time elapsed: 158 ms
[12:30:34 INFO]: Running delayed init tasks
[12:30:34 INFO]: Done (3.067s)! For help, type "help"
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 11. When Paper for Minecraft 1.17 is
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 11 will
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 1.8.0_281
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information:
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java11
[12:30:34 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
```
 이거 왜이런가요?

**Comment by ghost** [comment]
아 코틀린 적용이 안된거였군요
